---
title: "Assignment 6"
output: pdf_document
header-includes:
  - \usepackage{diagbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', out.width = '75%', fig.asp = .75)
#library(tidyverse)
```

# Question 1

Let $X$ and $Y$ have the following joint distribution:

$$\begin{tabular}{c|ccc}
\diagbox{X}{Y} & -1 & 0 & 1 \\
\hline 
-1 & 1/6 & 0 & 1/6 \\
0 & 1/3 & 0 & 0 \\
1  & 1/6 & 0 & 1/6 \\
\end{tabular}$$

(a) Find the covariance between $X$ and $Y$.
(b) Find $P(X = -1|Y = 1)$.
(c) Show that $X$ and $Y$ are dependent.


# Question 2

Emily and Albert are getting married and are looking at combining their finances. Both work in sales, so they have salaries that vary from month to month. They want to know if they can afford to buy a house with payments of \$1350 per month. They only want to spend 30\% of their total income on house payments. If Emily’s average sales are \$3000 per month with a standard deviation of \$500 and Albert's average sales are \$2000 with a standard deviation of \$1000, and both sales are normally distributed with a covariance between Emily's sales and Albert's sales of 10000 dollars^2^, what percent of the time will they be able to spend less than 30\% of their total income on their house payment?

# Question 3

If $f(x, y) = e^{-(x+y)}$, $x > 0$, and $y > 0$, find $P(X+3>Y|X >1/3)$.

# Question 4

If $f(x,y)=k(y-2x)$ is a joint density function over $0<x<1$, $0<y<1$, and $y>x^2$, then what is the value of the constant $k$?

# Question 5

Let $X$ and $Y$ denote the heart rate (in beats per minute) and average power output (in watts) for a 10-minute cycling time trial performed by a professional cyclist. Assume that $X$ and $Y$ have a bivariate normal distribution with parameters $\mu_X=180$, $\sigma_X=10$, $\mu_Y=400$, $\sigma_Y=50$, and $\rho=0.9$. Find

(a) $E[Y|X=170]$,

(b) $E [ Y | X = 200]$,

(c) $Var [ Y | X = 170]$,

(d) $Var [ Y | X = 200]$,

(e) $P(Y\le 380|X = 170)$, and

(f) $P (Y \ge 450 | X = 200)$.

# Question 6

The wait time in minutes a shopper spends in a local supermarket's checkout line has distribution

$$f(x)=\frac{1}{2}e^{-x/2},x>0.$$
On weekends, however, the wait is longer, and the distribution then is given by

$$g(x)=\frac{1}{3}e^{-x/3},x>0.$$
Assume that the day a person shops is uniformly distributed across the week, find:

(a) The probability that the waiting time for a customer will be less than 1. 

(b) The probability that, given a waiting time of less than 2 minutes, it will be a weekend.

(c) The probability that the customer waits less than 2 minutes.

# Question 7

Assume the distribution of grades for a particular group of students has a bivariate normal distribution with parameters $\mu_X=3.2$, $\sigma_X=0.4$, $\mu_Y=2.4$, $\sigma_Y=0.6$, and $\rho=0.6$, where $X$ and $Y$ represent the grade point averages in high school and the first year of college, respectively.

(a) Set the seed equal to 194 (`set.seed(194)`), and use the function `mvrnorm()` from the `MASS` package to simulate the population, assuming the population of interest consists of 200 students. (Hint: Use `empirical = TRUE`.)

(b) Compute the means of $X$ and $Y$ . Are they equal to 3.2 and 2.4, respectively?

(c) Compute the variance of $X$ and $Y$ as well as the covariance between $X$ and $Y$. Are the values 0.16, 0.36, and 0.144, respectively?

(d) Create a scatterplot of $Y$ versus $X$. If a different seed value is used, how do the simulated numbers differ?

# Question 8

Show that if $X_1,X_2,...,X_n$ are independent random variables with means $\mu_1,\mu_2,...,\mu_n$ and variances $\sigma^2_1,\sigma^2_2,...,\sigma^2_n$, respectively, then the mean and variance of $Y=\sum_{i=1}^n c_i X_i$, where the $c_i$s are real-valued constants, are $\mu_Y= \sum_{i=1}^n c_i\mu_i$ and $\sigma^2_Y= \sum_{i=1}^n c^2_i \sigma^2_i$.
