---
title: "Assignment 8"
output: pdf_document
#header-includes:
#  - \usepackage{diagbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', out.width = '75%', fig.asp = .75)
#library(tidyverse)
```

# Question 1

Given the estimators of the mean $T_1 = (X_1 + 2X_2 + X_3)/4$ and $T_2 = (X_1 + X_2 + X_3)/3$, where $X_1$, $X_2$, $X_3$ is a random sample from a $N(\mu,\sigma^2)$ distribution, prove that $T_2$ is more
efficient than $T_1$.


# Question 2

Let $X$ be a $Bin(n,p)$ random variable.

(a) Find the mean squared error of the $p$ parameter estimators $T_1 = X/n$ and $T_2 =(X + 2)/(n + 4)$.

(b) When $n = 20$ and $p = 0.4$, which estimator, $T_1$ or $T_2$, has the smaller MSE?

(c) Plot the efficiency of $T_2$ relative to $T_1$ versus $p$ values in $(0, 1)$ for $n$ values from 1 to 10.

# Question 3

Consider a random sample of size $n$ from a geometric distribution.

(a) Find the method of moments estimator of $p$.

(b) Find the maximum likelihood estimator of $p$.

(c) Use the results from (a) and (b) to compute the method of moments and maximum likelihood estimates from the sample {8, 1, 2, 0, 0, 0, 2, 1, 3, 3}, which represents the number of Bernoulli trials that resulted in failure before the first success in 10 experiments.

# Question 4

Consider the density function

$$f(x)=(\theta+1)(1-x)^\theta,0 \le x \le 1, \theta>0.$$

(a) Find the maximum likelihood estimator of $\theta$ for a random sample of size $n$.


(b) Set the seed equal to 3, and generate 20,000 values from $f(x)$ when $\theta = 5$. Calculate the maximum likelihood estimate of $\theta$ from the generated values.

(c) How close is the maximum likelihood estimate in (b) to $\theta = 5$?

# Question 5

Consider an exponential distribution with mean $\theta$ and the following estimators of $\theta$:

$$\hat{\theta_1}=X_1, \hat{\theta_2}=\frac{1}{2}(X_1+X_2), \hat{\theta_3}=\min{(X_1,X_2,X_3)}.$$

(a) Find the mean and variance of each estimator.

(b) Are any of the estimators efficient?

(c) Which estimator is the MLE?

(d) Let $X$ be an exponential random variable with mean $\theta + 2$. Which estimator is an unbiased estimator of $\theta$?

# Question 6

Consider the density function

$$f(x) = 3\pi \theta x^2 e^{-\theta \pi x^3}, x \ge 0.$$

(a) Set the seed equal to 102, and generate a random sample of size $n = 20,000$ with $\theta = 5$.

(b) Find the sample mean and the sample variance of the random values generated in (a).

(c) Create a density histogram of the simulated values from (a) and superimpose the density function over the density histogram.

(d) Find the maximum likelihood estimate of $\theta$.

(e) Plot the logarithm of the likelihood function versus $\theta$. Use values for $\theta$ from 0 to 15.

