---
title: "Advanced Statistics HW9"
author:  "Due date: December 5, 2018"
output: pdf_document
#header-includes:
#  - \usepackage{diagbox}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', out.width = '75%', fig.asp = .75)
#library(tidyverse)
```

# Exercises 1

Given a random sample $X_1, X_2, ... , X_n$ from a normal population $N(\mu, \sigma^2)$, where $\sigma^2$ is known:

(a) What is the confidence level for the interval
$\bar{x} \pm 2.053749\sigma/\sqrt{n}$ ?

(b) What is the value of the percentile $z_{\alpha/2}$ for a 99% confidence interval?


# Exercises 2

A historic data set studied by R.A. Fisher is the measurements in centimeters of four flower parts (sepal length, sepal width, petal length, and petal width) on 50 specimens for each of three species of irises (Setosa, Versicolor, and Virginica). The data are stored in
the data frame `iris` (Fisher, 1936).

(a) Analyze the sepal lengths for Setosa, Versicolor, and Virginica irises, and comment on the characteristics of their distributions.

(b) Based on the analysis from part (a), construct an appropriate 99% confidence interval for the mean sepal length of Setosa irises.

# Exercises 3

Let $X_1, ..., X_{19}$ and $Y_1, ..., Y_{15}$ be two random samples from a $N(\mu_X, \sigma^2_X)$ and a $N(\mu_Y, \sigma^2_Y)$, respectively. Suppose that $\bar{x} = 57.3, s^2_X = 8.3, \bar{y} = 65.6$, and $s^2_Y = 9.7$. Find a 96% confidence interval for $\mu_X, \mu_Y$, and $\mu_X-\mu_Y$.

# Excercise 4

Given the following data {25.3 23.8 27.5 23.2 24.5 25.3 24.6 26.8 25.9 29.2},

(a) State the assumption(s) needed to construct a confidence interval for the population variance.

(b) Assuming your assumption(s) in (a) are satisfied, construct a 95% confidence interval for $\sigma^2$.

(c) Assuming that $\mu = 25$, construct a 95% confidence interval for $\sigma^2$.

# Excercise 5

A large company wants to estimate the proportion of its accounts that are paid on time.

(a) How large a sample is needed to estimate the true proportion within 4% with a 95% confidence interval?

(b) Suppose 650 out of 800 accounts are paid on time. Construct a 98% confidence interval for the true proportion of accounts that are paid on time.

